apiVersion: apps/v1
kind: Deployment
metadata:
  name: winter-gallery
  labels:
    app: winter-gallery
spec:
  replicas: 3
  selector:
    matchLabels:
      app: winter-gallery
  template:
    metadata:
      labels:
        app: winter-gallery
    spec:
      containers:
      - name: winter-gallery
        image: tapashranjannandi/winter-galary:latest  
        ports:
        - containerPort: 80
