apiVersion: v1
kind: Service
metadata:
  name: winter-gallery-service
spec:
  selector:
    app: winter-gallery 
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007 
